#NOTE: if you delete this file, make sure
#####  you generate  a new symlink between this
#####  and the alacritty.yml file in
#####  path_to_alacritty.yml_concrete_file

##########
# WINDOW #
##########
window:
  padding:
    x: 3
    y: 3
  decorations: full
  opacity: 0.95

########
# FONT #
########
font:
  normal:
    family: Hack Nerd Font
    style: Regular
  size: 11.0
draw_bold_text_with_bright_colors: true

##########
# CURSOR #
##########
cursor:
  style:
    Values for `shape`: null
    shape: Block
    blinking: on
  blink_interval: 500
  unfocused_hollow: true

#########
# MOUSE #
#########
mouse:
  hide_when_typing: true

################
# KEY BINDINGS #
################
key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: S, mods: Control|Shift, action: SearchBackward }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }

################
# ZENBURN FONT #
################
schemes:
  # Default colors
  primary:
    background: '0x383838'
    foreground: '0xdcdccc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x383838'
    cursor: '0xdcdccc'

  # Normal colors
  normal:
    black: '0x383838'
    red: '0xdca3a3'
    green: '0x5f7f5f'
    yellow: '0xe0cf9f'
    blue: '0x7cb8bb'
    magenta: '0xdc8cc3'
    cyan: '0x93e0e3'
    white: '0xdcdccc'

  # Bright colors
  bright:
    black: '0x6f6f6f'
    red: '0xdca3a3'
    green: '0x5f7f5f'
    yellow: '0xe0cf9f'
    blue: '0x7cb8bb'
    magenta: '0xdc8cc3'
    cyan: '0x93e0e3'
    white: '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xdfaf8f' }
    - { index: 17, color: '0x000000' }
    - { index: 18, color: '0x404040' }
    - { index: 19, color: '0x606060' }
    - { index: 20, color: '0x808080' }
    - { index: 21, color: '0xc0c0c0' }
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black: '#282828'
    red: '#cc241d'
    green: '#98971a'
    yellow: '#d79921'
    blue: '#458588'
    magenta: '#b16286'
    cyan: '#689d6a'
    white: '#a89984'

  # Bright colors
  bright:
    black: '#928374'
    red: '#fb4934'
    green: '#b8bb26'
    yellow: '#fabd2f'
    blue: '#83a598'
    magenta: '#d3869b'
    cyan: '#8ec07c'
    white: '#ebdbb2'
theme: Gruvbox-Dark
